import React, { useState, useEffect } from 'react';

const CourseReader = ({ subject, onBack }) => {
  const [tree, setTree] = useState([]);
  const [selectedNode, setSelectedNode] = useState(null);
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);

  // Load the Curriculum Tree from the new backend endpoint
  useEffect(() => {
    const fetchTree = async () => {
      const res = await fetch(`https://ascenda-production.up.railway.app/api/curriculum/subjects/${subject.id}/tree`);
      const data = await res.json();
      setTree(data);
    };
    fetchTree();
  }, [subject.id]);

  // Fetch AI content when a leaf node is selected
  useEffect(() => {
    if (!selectedNode) return;
    const fetchContent = async () => {
      setLoading(true);
      const res = await fetch(`https://ascenda-production.up.railway.app/api/content/fetch/${selectedNode.id}`);
      const data = await res.json();
      setContent(data.body || "Content currently being generated by AI...");
      setLoading(false);
    };
    fetchContent();
  }, [selectedNode]);

  return (
    <div className="flex h-screen bg-slate-950 text-white">
      {/* LEFT PANEL: The Tree Sidebar */}
      <aside className="w-80 border-r border-slate-800 bg-slate-900/20 overflow-y-auto">
        <div className="p-6 border-b border-slate-800">
          <button onClick={onBack} className="text-[10px] text-slate-500 hover:text-white uppercase tracking-widest mb-4">← Back</button>
          <h2 className="text-xl font-bold">{subject.name}</h2>
        </div>
        <nav className="p-4 space-y-4">
          {tree.map(chapter => (
            <div key={chapter.id}>
              <h3 className="text-xs font-bold text-slate-500 uppercase px-2 mb-2 tracking-tighter">{chapter.title}</h3>
              <div className="space-y-1">
                {chapter.children?.map(topic => (
                  <button
                    key={topic.id}
                    onClick={() => setSelectedNode(topic)}
                    className={`w-full text-left p-2 px-4 rounded-lg text-sm transition-all ${
                      selectedNode?.id === topic.id ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:bg-slate-800'
                    }`}
                  >
                    {topic.title}
                  </button>
                ))}
              </div>
            </div>
          ))}
        </nav>
      </aside>

      {/* RIGHT PANEL: The Reader */}
      <main className="flex-grow p-12 overflow-y-auto bg-slate-950">
        <div className="max-w-3xl mx-auto">
          {selectedNode ? (
            <div className={loading ? "opacity-50" : "opacity-100"}>
              <h1 className="text-4xl font-black mb-8">{selectedNode.title}</h1>
              <div className="prose prose-invert max-w-none text-slate-300">
                {content}
              </div>
            </div>
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-slate-600">
              <div className="text-6xl mb-4">📚</div>
              <p>Select a topic from the curriculum tree to begin.</p>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default CourseReader;